[project]
name = "jaseci-studio"
version = "0.1.0"
description = "Developer workbench for Jac applications"
entry-point = "main.jac"

[dependencies.npm]
jac-client-node = "1.0.4"

[dependencies.npm.dev]
"@jac-client/dev-deps" = "1.0.0"

[dev-dependencies]
watchdog = ">=3.0.0"

[serve]
base_route_app = "app"

[plugins.client]
